#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_concert/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import argparse
import rospy
import rocon_python_comms
import rocon_python_utils
import rocon_console.console as console
import rocon_std_msgs.msg as rocon_std_msgs

import sys
import signal
from PyQt4 import QtGui, QtCore

##############################################################################
# Globals
##############################################################################

topic_name = '/map_server/map' ## THIS NEEDS TO BE CHANGED TO MAP SOMETHING

##############################################################################
# Classes
##############################################################################


class Window(QtGui.QWidget):

    def __init__(self, description):
        super(Window, self).__init__()
        self._description = description
        self.initUI()

    def initUI(self):
        self.text = QtGui.QLabel(self)
        self.text.resize(200, 200)
        self.text.move(100 + 10, 0)
        self.text.setText("<br/><b>Description:</b> %s" % (self._description))
        self.text.setWordWrap(True)
        self.text.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)

        self.button = QtGui.QPushButton(self)
        self.button.setText("Select Your Map")
        self.button.clicked.connect(self.selectFile)
        self.button.move(100+50, 0)
        self.button.show()

    def selectFile(self):
        self.text.setText(QtGui.QFileDialog.getOpenFileName(self, 'Select Your Map', '.'))
    #     self.putUnderMouse()

    # def putUnderMouse(self):
    #     mouse = QtGui.QCursor.pos()
    #     self.move(mouse.x() - (210 + self.pic.geometry().width()) / 2,
    #                 mouse.y() - (self.pic.geometry().height()) / 2)



##############################################################################
# Main
##############################################################################

if __name__ == '__main__':

    description = 'Please select the map you would like to load'
    app = QtGui.QApplication(sys.argv)
    window = Window(description)
    window.show()
    sys.exit(app.exec_())